global using Asp.Versioning;
global using Asp.Versioning.ApiExplorer;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.OpenApi.Models;
global using Refactor.PaymentGate.Api.Abstractions;
global using Refactor.PaymentGate.Api.Abstractions.CQRS;
global using Refactor.PaymentGate.Api.Abstractions.DDD.Specifications;
global using Refactor.PaymentGate.Api.Abstractions.Errors;
global using Refactor.PaymentGate.Api.Abstractions.Responses;
global using Refactor.PaymentGate.Api.Abstractions.Results;
global using Refactor.PaymentGate.Api.Abstractions.Validators;
global using Refactor.PaymentGate.Api.Datas;
global using Refactor.PaymentGate.Api.Extensions;
global using Refactor.PaymentGate.Api.OperationFilters;
global using Refactor.PaymentGate.Api.Options;
global using Refactor.PaymentGate.Api.PaymentOrganizations;
global using Refactor.PaymentGate.Api.PaymentOrganizations.Filtering;
global using Refactor.PaymentGate.Api.PaymentOrganizations.Persistences;
global using Refactor.PaymentGate.Api.PaymentOrganizations.Sorting;
global using Refactor.PaymentGate.Api.PaymentOrganizations.UseCases.Create;
global using Refactor.PaymentGate.Api.PaymentOrganizations.ValueObjects;
global using Refactor.PaymentGate.Api.Pipelines;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Text;
global using static Microsoft.EntityFrameworkCore.EntityState;
global using static Refactor.PaymentGate.Api.Abstractions.CollectionUtilities;
global using static Refactor.PaymentGate.Api.Abstractions.Constants.Constants;
global using static Refactor.PaymentGate.Api.Abstractions.Constants.Constants.CustomType;
global using static Refactor.PaymentGate.Api.Abstractions.Constants.Constants.ProblemDetails;
global using static Refactor.PaymentGate.Api.Abstractions.CoreUtilities;
global using static Refactor.PaymentGate.Api.Abstractions.EnumUtilities;
global using static Refactor.PaymentGate.Api.Abstractions.Errors.ErrorUtilities;
global using static Refactor.PaymentGate.Api.Abstractions.ListUtilities;
global using static Refactor.PaymentGate.Api.Abstractions.Results.ResultExtensions;
global using static Refactor.PaymentGate.Api.PaymentOrganizations.Errors.DomainError;
global using IHttpResult = Microsoft.AspNetCore.Http.IResult;
global using IResult = Refactor.PaymentGate.Api.Abstractions.Results.IResult;
global using ValidationResult = Refactor.PaymentGate.Api.Abstractions.Results.ValidationResult;
